[versions]
# kotlin version
kotlin = "2.0.10"

# plugin third party version
arturboschDetektPlugin = "1.23.7"
jlleitschuhKtlintPlugin = "12.1.1"

[libraries]
# kotlin libraries
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# mockk libraries
io-mockk = { group = "io.mockk", name = "mockk", version = "1.13.13" }

org-eclipse-jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version = "7.0.0.202409031743-r" }
org-junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }

[plugins]
# kotlin plugin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# third party plugin
io-gitlab-arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "arturboschDetektPlugin" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "jlleitschuhKtlintPlugin" }

