name: Pull request validation

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  validate:
    uses: swordsteel/hlaeja-common-workflows/.github/workflows/run-checks.yml@master
    secrets:
      CI_BOT_PAT: ${{ secrets.CI_BOT_PAT }}
